[pytest]
log_cli = true
log_cli_level = INFO
log_format = %(message)s
markers =
    smoke: быстрые тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    ui: UI-тесты
    db: DB-тесты
    skip_authenticated_user_cleanup: пропустить очистку authenticated_user после теста
